# Generated by Django 4.1.1 on 2022-11-10 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="userInformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userweight", models.IntegerField()),
                ("userage", models.IntegerField()),
                ("userlength", models.IntegerField()),
                ("userrepastlength", models.IntegerField()),
                (
                    "userchoice",
                    models.CharField(
                        choices=[("KG+", "KİLO ALMA"), ("KG-", "KİLO VERME")],
                        default="KİLO VERME",
                        max_length=10,
                    ),
                ),
                ("userweightrange", models.IntegerField(default=0)),
                (
                    "usermoving",
                    models.CharField(
                        choices=[
                            ("az", "Az Hareketli"),
                            ("cok", "Cok Hareketli"),
                            ("orta", "Orta Hareketli"),
                            ("asiri", "Aşırı Hareketli"),
                        ],
                        default="Az Hareketli",
                        max_length=100,
                    ),
                ),
                ("bmr", models.SmallIntegerField(default=0)),
                ("MUZZ", models.BooleanField(default=True, null=True)),
                ("HURMA", models.BooleanField(default=False, null=True)),
                ("PRE_WORKOUT", models.BooleanField(default=False, null=True)),
                ("CHURCILL", models.BooleanField(default=False, null=True)),
                ("BCAA", models.BooleanField(default=False, null=True)),
                ("KAHVE", models.BooleanField(default=False, null=True)),
                (
                    "ogun1protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun2protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun3protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun4protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun5protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun6protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun7protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun8protein",
                    models.CharField(
                        choices=[
                            ("Tavuk Göğsü", "Tavuk Göğsü"),
                            ("Balık (Çupra)", "Balık (Çupra)"),
                            ("Hindi", "Hindi"),
                        ],
                        default="Tavuk Göğsü",
                        max_length=100,
                    ),
                ),
                (
                    "ogun1karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun2karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun3karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun4karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun5karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun6karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun7karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "ogun8karb",
                    models.CharField(
                        choices=[
                            ("Pirinç", "Pirinç"),
                            ("Bulgur", "Bulgur"),
                            ("Yulaf", "Yulaf"),
                            ("Makarna", "Makarna"),
                            ("Ekmek", "Ekmek"),
                        ],
                        default="Pirinç",
                        max_length=100,
                    ),
                ),
                (
                    "userid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
