# Generated by Django 4.1.1 on 2022-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformations",
            name="ogun1protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun2protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun3protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun4protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun5protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun6protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun7protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userinformations",
            name="ogun8protein",
            field=models.CharField(
                choices=[
                    ("Tavuk Göğsü", "Tavuk Göğsü"),
                    ("Balık", "Balık"),
                    ("Hindi", "Hindi"),
                ],
                default="Tavuk Göğsü",
                max_length=100,
            ),
        ),
    ]
