# Generated by Django 4.1.1 on 2022-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_alter_userinformations_ogun1protein_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformations",
            name="usergender",
            field=models.CharField(
                choices=[("ERKEK", "ERKEK"), ("KADIN", "KADIN")],
                default="Kadın",
                max_length=100,
            ),
        ),
    ]
