# Generated by Django 4.1.1 on 2022-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programTitle", models.CharField(max_length=150)),
                ("programExplanation", models.TextField()),
                ("programImage", models.ImageField(upload_to="programlar/images")),
            ],
        ),
    ]
