# Generated by Django 4.1.1 on 2022-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programlar",
            name="programAbstract",
            field=models.TextField(default="Program Özeti"),
        ),
        migrations.AlterField(
            model_name="programlar",
            name="programImage",
            field=models.ImageField(upload_to="djangouploads/programlar/images"),
        ),
    ]
