# Generated by Django 4.1.1 on 2022-10-27 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_programlar_programabstract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programTitle", models.CharField(max_length=150)),
                ("programAbstract", models.TextField(default="Program Özeti")),
                ("programExplanation", ckeditor.fields.RichTextField()),
                (
                    "programImage",
                    models.ImageField(upload_to="djangouploads/programlar/images"),
                ),
            ],
        ),
        migrations.DeleteModel(name="Programlar",),
    ]
