# Generated by Django 4.1.1 on 2022-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_program_programtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="programTitle",
            field=models.SlugField(allow_unicode=True, max_length=150),
        ),
    ]
