# Generated by Django 4.1.1 on 2022-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_program_programtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="programTitle",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
