# Generated by Django 4.1.1 on 2022-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_program_programtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="programExplanation",
        ),
        migrations.AlterField(
            model_name="program",
            name="programTitle",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
