# Generated by Django 4.1.1 on 2022-11-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_program_programexplanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="programFullImage",
            field=models.ImageField(
                null=True, upload_to="cagewebapp/djangouploads/programlar/images"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="programImage",
            field=models.ImageField(
                null=True, upload_to="cagewebapp/djangouploads/programlar/images"
            ),
        ),
    ]
