# Generated by Django 4.1.1 on 2022-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_program_programfullimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="programImage",
            field=models.ImageField(
                null=True, upload_to="djangouploads/programlar/images"
            ),
        ),
    ]
